### ISSUE TITLE
FAB went to the wrong place when open the bottom bar 

### ISSUE THREAD

**Issue by JoeSteven** [rubensousa/FloatingToolbar#12]
hey man
I think there is a bug .when click the fab open the bottom bar ,then scroll the recyclerview ,the FAB will go to a wrong place .
also ,sometimes the FAB can't show icon~ how to post a picture?

**Comment by rubensousa** [comment]
Hi, there's another issue still open that refers to this. #6
I'm going to close this one in favor of the old one. I'm currently busy and didn't have time to fix this yet.

Regarding the FAB icon, please create a new issue.
You can attach files by dragging and dropping or selecting them.

![demo](https://cloud.githubusercontent.com/assets/10662096/16362316/f7ba6062-3ba3-11e6-9f38-f9662fe12772.gif)
