### ISSUE TITLE
FAB can't show icon sometimes

### ISSUE THREAD

**Issue by JoeSteven** [rubensousa/FloatingToolbar#13]
like this 
![2ea9052efc65aa4203d9266a27537961](https://cloud.githubusercontent.com/assets/16322233/16371927/31cda380-3c7c-11e6-8374-322b9ef7f9eb.jpg)

**Comment by rubensousa** [comment]
I think this is due to the drawable animation. I also noticed this in the latest dev branch. I'll remove it since it's noticeable.

**Comment by rubensousa** [comment]
Fixed in commit:https://github.com/rubensousa/FloatingToolbar/commit/a0270efe552fa67d21a1987d08f324bb70190162

Will be out in 0.4
