### ISSUE TITLE
FAB goes to the wrong place

### ISSUE THREAD

**Issue by tearfulDalvik** [rubensousa/FloatingToolbar#16]
FAB goes to the wrong place after collapsed toolbar.
(Not on every devices, until now I haven't seen it)
1.http://coolapk.com/r/2vuz
2.http://image.coolapk.com/feed/2016/0804/577017_1470283978_9899.gif

These were reported by different users.

**Comment by rubensousa** [comment]
This should be fixed with #15.
I'll try to release the update today.

**Comment by rubensousa** [comment]
1.1.0 is released. Feel free to reopen if it's still happening. I've updated the sample with the AppBar so you can test this by focusing the EditText
