### ISSUE TITLE
onMorphEnd seems to be called twice

### ISSUE THREAD

**Issue by bradmont** [rubensousa/FloatingToolbar#18]
Hi, I'm setting up transparent view to click & dismiss the toolbar; it appears & disappears with the FloatingToolbar. I'm using a MorphListener, and it looks like onMorphEnd is being called twice when I open the FloatingToolbar. The other callbacks only fire once.

It isn't urgent and isn't causing any troubles for me, but I figured it should be reported.

**Comment by rubensousa** [comment]
I'll take a look at this tomorrow. Thanks!

**Comment by rubensousa** [comment]
Are you using 1.3.0? This should be fixed by: https://github.com/rubensousa/FloatingToolbar/commit/037bc57a1103b5f26a46b2c25e4c049655953448

**Comment by rubensousa** [comment]
Closing due to no answer. Feel free to reopen if this is still happening on 1.3.0

**Comment by bradmont** [comment]
I'm terribly sorry, I forget to get back to you. No, I wasn't using the latest version. Thanks!
