### ISSUE TITLE
1.3.0 FloatingToolbar exception and MenuItem text suggestion

### ISSUE THREAD

**Issue by xisvaldo** [rubensousa/FloatingToolbar#19]
When inserting `FloatingToolbar` in a xml file, it throws the following:
`java.lang.NoSuchFieldError: floatingtoolbar_start_elevation
	at com.github.rubensousa.floatingtoolbar.FloatingToolbar.<init>(FloatingToolbar.java:138)
	at com.github.rubensousa.floatingtoolbar.FloatingToolbar.<init>(FloatingToolbar.java:93)`

Also, there's a suggestion: I was looking at `FloatingToolbar.addMenuItems()` and realized that only images are added. It would be useful if could check if there is an `item.getTitle()` and add it as a `TextView`.

**Comment by rubensousa** [comment]
Are you overriding floatingtoolbar_start_elevation somewhere? If you are, it gets stripped from the library resources. Check out this SO post: http://stackoverflow.com/questions/37460385/android-java-lang-nosuchfielderror-rlayout-e

As you can see, this doesn't happen in the sample.


Regarding the suggestion, I'll try to see if it looks good. If it does, I'll include that in 1.4.0

**Comment by xisvaldo** [comment]
Well I just "Invalidated Cache and Restarted" and seems to be all good now. Anyway, thanks for you quick answer and support.
