### ISSUE TITLE
Setting padding doesn't work right

### ISSUE THREAD

**Issue by nadavfima** [rubensousa/FloatingToolbar#20]
If i set paddingBottom at 48dp for example, and set the height to 104dp (56dp + 48dp), it just squeezes everything to the top and then cuts it.

In this screenshot the actions should just appear as usual above the navbar.

![screenshot_20170127-135907](https://cloud.githubusercontent.com/assets/688836/22370317/7da0a846-e499-11e6-8b0c-f15fa517dc5d.png)

**Comment by rubensousa** [comment]
Can you check the develop's branch sample and see if this commit fixed it for you? https://github.com/rubensousa/FloatingToolbar/commit/8d697b158aa5b8b14c036d9617d5646900c50295

Thanks :)

**Comment by nadavfima** [comment]
Yup, that fixed it.
Thanks!

**Comment by nadavfima** [comment]
When can I expect a new version on master?

**Comment by rubensousa** [comment]
You can expect an update today :)

**Comment by rubensousa** [comment]
1.3.1 released
