### ISSUE TITLE
can't use "findViewById" to get FloatingToolbar instance

### ISSUE THREAD

**Issue by Melonl** [rubensousa/FloatingToolbar#21]
When I use "findViewById" to get instance,the compiler give me an error "An instance of type 'android.view.View' can not be of type 'com.github.rubensousa.floatingtoolbar.FloatingToolbar' ".I replaced the library version of sample with 1.4.1 and got the same error. My English is not good, please forgive me.

**Comment by rubensousa** [comment]
You're trying to cast a View to a FloatingToolbar. Check your xml again and make sure you're passing the FloatingToolbar's id.

**Comment by Melonl** [comment]
I make sure the xml and id is ok.The FloatingToolbar's id has passed.I wouldn't make such a simple mistake.But I still  got  same error.Now I am using the 1.1.1 version of the library, it can work, but 1.4.1 can not work.Isn't it really bug?

**Comment by rubensousa** [comment]
Can you post your XML and the relevant code? This isn't happening in the sample

**Comment by Melonl** [comment]
My xml and the java code is completely copy from the sample , you can try to replace  the sample's library version with 1.4.1 to test.

**Comment by rubensousa** [comment]
I did use 1.4.1 and test the sample. It's an issue on your side. You're casting a View that's not a FloatingToolbar.

**Comment by Melonl** [comment]
OK，I'm just trying to help you. I'm very sorry for any inconvenience I've caused you.

**Comment by rubensousa** [comment]
I appreciate it, but without providing more info, I can't help.

**Comment by Melonl** [comment]
By the way , How to stop animation when FloatingToolBar is showing ?

**Comment by rubensousa** [comment]
I didn't understand, sorry. You mean showing without animating?

**Comment by Melonl** [comment]
I mean, how can I stop it when the FloatingToolbar is showing with animating ? (at this time , the isShowing() returns true. For example, I called show(), and then I tried to call hide() )

**Comment by rubensousa** [comment]
You can't cancel the animation. If you want to hide it after showing, use .hide() inside the onUnmorphEnd from MorphListener: https://github.com/rubensousa/FloatingToolbar/blob/master/floatingtoolbar/src/main/java/com/github/rubensousa/floatingtoolbar/FloatingToolbar.java#L562

**Comment by Melonl** [comment]
That's OK. Thank you very much!
