### ISSUE TITLE
Many menuitems => "more" button?

### ISSUE THREAD

**Issue by greg-stein** [rubensousa/FloatingToolbar#25]
Hi, 

Is there a possibility to get handling of "ifRoom" menu item mode like in regular menus on ToolBar?
The app could be used on devices with different screen sizes and hence you cannot know easily how to layer the items in the menu.

**Comment by rubensousa** [comment]
No, sorry. I don't think the more button is appropriate for the toolbar. You can always use a custom view.

**Comment by greg-stein** [comment]
Thank you!
