### ISSUE TITLE
My own View on the FloatingToolBar

### ISSUE THREAD

**Issue by greg-stein** [rubensousa/FloatingToolbar#26]
Hi,

I wanted to place a Spinner on the Toolbar, but it is simply not shown. I do have menu as well.
`
    <com.github.rubensousa.floatingtoolbar.FloatingToolbar
        android:id="@+id/floatingToolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:layout_gravity="bottom"
        app:floatingMenu="@menu/menu_edit_mode"
        app:floatingAutoHide="false"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:android="http://schemas.android.com/apk/res/android" >

        <Spinner
            android:id="@+id/add_spinner"
            android:layout_width="50dp"
            android:layout_height="match_parent" />

    </com.github.rubensousa.floatingtoolbar.FloatingToolbar>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|start"
        android:layout_margin="@dimen/fab_margin"
        app:fabSize="mini"
        android:src="@drawable/ic_mode_edit_white_24dp" />
`

**Comment by rubensousa** [comment]
Use app:floatingCustomView with your custom layout.
