### ISSUE TITLE
Using it in DrawerLayout causes wrong

### ISSUE THREAD

**Issue by drogbababa** [rubensousa/FloatingToolbar#27]
I want to use FloatingToolBar in a DrawerLayout,
but it causes "Error inflating class com.github.rubensousa.floatingtoolbar.FloatingToolbar" in XML file.
How can i solve it?

**Comment by rubensousa** [comment]
Please, post your xml. I can use it inside a DrawerLayout if I wrap it inside another FrameLayout or CoordinatorLayout.

**Comment by drogbababa** [comment]
Yes! I can use it when I wrap it inside a FrameLayout. Thank you for the answer!
