### ISSUE TITLE
Can you please add an option to set the items programmatically?

### ISSUE THREAD

**Issue by jahirfiquitiva** [rubensousa/FloatingToolbar#28]
Thanks in advance

**Comment by rubensousa** [comment]
I'll see what I can do. There's already an option to set a menu, which you can build it yourself, but I'll see if I can add an easier way

**Comment by jahirfiquitiva** [comment]
@rubensousa 

Thanks. I forked your repo yesterday and did this already. I'm about to make a PR. I hope you merge it :)

**Comment by rubensousa** [comment]
Added in 1.5.0

**Comment by jahirfiquitiva** [comment]
@rubensousa 

Thanks but I don't see a way to set the menu id programmatically, so I think there's no way to make the onClick listener work always, since getting the id would not work.

Check #33
