### ISSUE TITLE
Allow removing all morph listeners

### ISSUE THREAD

**Issue by jahirfiquitiva** [rubensousa/FloatingToolbar#31]
I had an issue with the library when I needed to do this, because the old listener wasn't removed properly for some reason.

I added this in my work and since then, the morph listeners work just as I want them to.

The thing don't want to have a global morph listener and re-add it or remove it when needed.

Thanks in advance

**Comment by rubensousa** [comment]
I'm 100% sure this an user error, but I've added it anyway in https://github.com/rubensousa/FloatingToolbar/commit/5381664a4da87be7b7d69708b80ea525d1de9ee2.
