### ISSUE TITLE
Creating menu programmatically does not have an option to set item id

### ISSUE THREAD

**Issue by jahirfiquitiva** [rubensousa/FloatingToolbar#33]
Without the id nor the position of the item, it is really hard to know exactly which button was clicked. 

The current FloatingToolbarMenuBuilder sets 0 as the item id always.

**Comment by rubensousa** [comment]
I don't even know how I forgot about this :(
Thanks once again. I've added it in: https://github.com/rubensousa/FloatingToolbar/commit/d6088e1f5a942876f8d5c60a96e713f5516be636

Can you please check out the current dev branch and check if it's enough for your use case? I'll release 1.5.1 once I get your feedback.

**Comment by jahirfiquitiva** [comment]
@rubensousa 

Great. Thank you... Btw, can you add some constructor that receive a normal int instead of only IdRes?  Removing the annotation could work too. Thanks again.

**Comment by rubensousa** [comment]
Yes, sure. Since you probably want to use ids that don't exist in other menus' xml, this makes sense.

**Comment by jahirfiquitiva** [comment]
@rubensousa 
Hmm, that totally sounded like sarcasm, so I don't know.
Another reason why I would want this is because I can treat the ids like positions. It's really useful for me.

**Comment by rubensousa** [comment]
It wasn't sarcasm at all, it makes really sense. I figured this after using the sample and trying to create the items manually ;)

**Comment by jahirfiquitiva** [comment]
@rubensousa 
Great. Thank you

**Comment by jahirfiquitiva** [comment]
@rubensousa 
Great. Thank you

**Comment by rubensousa** [comment]
Released on 1.5.1
